import { defineCollection, defineCollections } from 'vuepress-theme-plume'

const docs = [
  defineCollection({
    type: 'doc',
    dir: 'MachineLearning',
    linkPrefix: '/MachineLearning',
    title: '机器学习',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DataFoundry',
    linkPrefix: '/DataFoundry',
    title: '数据锻造坊',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/PyTorch',
    linkPrefix: '/DeepLearning/PyTorch',
    title: 'PyTorch',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/EpochalAlgorithms',
    linkPrefix: '/DeepLearning/EpochalAlgorithms',
    title: '跨时代算法',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/NetworkStructure',
    linkPrefix: '/DeepLearning/NetworkStructure',
    title: '网络结构',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/ActivationFunction',
    linkPrefix: '/DeepLearning/ActivationFunction',
    title: '激活函数',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/LossFunction',
    linkPrefix: '/DeepLearning/LossFunction',
    title: '损失函数',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/Optimizer',
    linkPrefix: '/DeepLearning/Optimizer',
    title: '优化器',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/Normalization',
    linkPrefix: '/DeepLearning/Normalization',
    title: '归一化',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'DeepLearning/EvaluationMetrics',
    linkPrefix: '/DeepLearning/EvaluationMetrics',
    title: '评价指标',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'ComputerVision',
    linkPrefix: '/ComputerVision',
    title: '计算机视觉',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'CodeExam',
    linkPrefix: '/CodeExam',
    title: '每日一题',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'Hobbies',
    linkPrefix: '/Hobbies',
    title: '逐趣成章',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
  defineCollection({
    type: 'doc',
    dir: 'desktop_app',
    linkPrefix: '/desktop_app',
    title: '桌面应用',
    autoFrontmatter: false,
    sidebar: 'auto',
  }),
]

export default defineCollections(docs)
